POST http://localhost:3000/api/auth/donatefood
Content-Type: application/json

{
  "foodname": "satyua",
  "email": "satya@examcple.com",
  "phonenumber": 1237890,
  "quantity": 11,
  "address": "123 satya St.express",
  "mealType": "satya",
  "categoryType": "satya",
  "district": "satya"
}



###
GET http://localhost:3000/api/auth/getdonations
Content-Type: application/json


###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "username": "Sribabu",
  "email": "sribabumandraju@gmail.com",
  "password": "sribabu@123"
}


###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
  "email": "sribabumandraju@gmail.com",
  "password": "sribabu@123"
}


###

PATCH http://localhost:3000/api/auth/updatedonation/66269f137f0cdb51fd2abf6a
Content-Type: application/json


  {
  "foodname": "Pizza1",
  "email": "examplesdmsdf nmsd1@example.com",
  "phonenumber": 1234567890,
  "quantity": 12,
  "address": "123 Mainsdmndm St.peterberg",
  "mealType": "Smfdmfupper",
  "categoryType": "Frenmfmch",
  "district": "Eafmfmstern"
}



###

DELETE http://localhost:3000/api/auth/deletedonation/662697e54e25c32d98f226f0
Content-Type: application/json

